# yaml-language-server: $schema=https://raw.githubusercontent.com/kjellberg/mrsk/validate-with-json-schema/lib/mrsk/configuration/schema.yaml

service: macro_tracker
image: bweave81/macro_tracker
servers:
  web:
    - <%= ENV["WEB_SERVER_IP"] %>
proxy:
  ssl: true
  host: macrotracker.bweave.dev
registry:
  username: bweave81
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  apps: server exec docker exec kamal-proxy kamal-proxy list
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "macro_tracker_v2_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
